-- STR
SELECT 
    a.MATCH_ID, a.MATCH_DATETIME, a.LEAGUE, a.HOME_TEAM, a.AWAY_TEAM, a.HOME_FT_GOAL, a.AWAY_FT_GOAL, 
    CASE 
        WHEN a.MATCH_DATETIME < '2020-06-01' THEN 'TRAIN'
        WHEN a.MATCH_DATETIME >= '2020-06-01' AND a.MATCH_DATETIME < '2020-09-01' THEN 'VAL'
        WHEN a.MATCH_DATETIME >= '2020-09-01' THEN 'TEST'
    END AS ML_TYPE,
    a.STR_HDA_HOME_MEAN, a.STR_HDA_AWAY_MEAN,
    a.STR_HDA_O_HKJC_H, a.STR_HDA_O_HKJC_A, 
    a.STR_HKJC_HILO_HANDICAP, a.STR_HKJC_HILO_HI, a.STR_HKJC_HILO_LO,
--    c.STR_MODE_HDC, c.STR_O_HKJC_HI, c.STR_O_HKJC_LO,
    b.HOME_AVG_GF, b.HOME_HOME_AVG_GF, b.AWAY_AVG_GF, b.AWAY_AWAY_AVG_GF,
    (b.HOME_HOME_GF+b.AWAY_AWAY_GA)/10 AS HOME_ADV, (b.HOME_HOME_GA+b.AWAY_AWAY_GF)/10 AS AWAY_ADV, (b.HOME_HOME_GF+b.AWAY_AWAY_GA)/10+(b.HOME_HOME_GA+b.AWAY_AWAY_GF)/10 AS GAME_POINT, 
    a.HOME_FT_GOAL+a.AWAY_FT_GOAL AS TOTAL_GOAL_COUNT
--    CASE WHEN a.HOME_FT_GOAL+a.AWAY_FT_GOAL>2 THEN 1 ELSE 0 END AS HILO_RESULT
FROM FULL_VIEW a, RECENT_RAW b, HILO_MERGE2 c
WHERE 
    a.MATCH_ID=b.MATCH_ID AND a.MATCH_ID=c.MATCH_ID
--    AND (c.STR_MODE_HDC=2.5 OR c.STR_MODE_HDC=2.75)
--    AND MATCH_DATETIME<'2020-09-01'
--    AND a.HOME_FT_GOAL IS NOT NULL
    AND a.STR_HDA_O_HKJC_H IS NOT NULL AND a.STR_HKJC_HILO_HANDICAP IS NOT NULL AND a.STR_HKJC_HILO_HI IS NOT NULL AND b.HOME_AVG_GF IS NOT NULL AND b.HOME_HOME_AVG_GF IS NOT NULL AND b.AWAY_AVG_GF IS NOT NULL AND b.AWAY_AWAY_AVG_GF IS NOT NULL
ORDER BY MATCH_DATETIME DESC;


-- END
SELECT 
    a.MATCH_ID, a.MATCH_DATETIME, a.LEAGUE, a.HOME_TEAM, a.AWAY_TEAM, a.HOME_FT_GOAL, a.AWAY_FT_GOAL, 
    CASE 
        WHEN a.MATCH_DATETIME < '2020-06-01' THEN 'TRAIN'
        WHEN a.MATCH_DATETIME >= '2020-06-01' AND a.MATCH_DATETIME < '2020-09-01' THEN 'VAL'
        WHEN a.MATCH_DATETIME >= '2020-09-01' THEN 'TEST'
    END AS ML_TYPE,
    a.END_HDA_HOME_MEAN, a.END_HDA_AWAY_MEAN,
    a.END_HDA_O_HKJC_H, a.END_HDA_O_HKJC_A, 
    a.END_HKJC_HILO_HANDICAP, a.END_HKJC_HILO_HI, a.END_HKJC_HILO_LO,
--    c.END_MODE_HDC, c.END_O_HKJC_HI, c.END_O_HKJC_LO,
    b.HOME_AVG_GF, b.HOME_HOME_AVG_GF, b.AWAY_AVG_GF, b.AWAY_AWAY_AVG_GF,
    (b.HOME_HOME_GF+b.AWAY_AWAY_GA)/10 AS HOME_ADV, (b.HOME_HOME_GA+b.AWAY_AWAY_GF)/10 AS AWAY_ADV, (b.HOME_HOME_GF+b.AWAY_AWAY_GA)/10+(b.HOME_HOME_GA+b.AWAY_AWAY_GF)/10 AS GAME_POINT, 
    a.HOME_FT_GOAL+a.AWAY_FT_GOAL AS TOTAL_GOAL_COUNT
--    CASE WHEN a.HOME_FT_GOAL+a.AWAY_FT_GOAL>2 THEN 1 ELSE 0 END AS HILO_RESULT
FROM FULL_VIEW a, RECENT_RAW b, HILO_MERGE2 c
WHERE 
    a.MATCH_ID=b.MATCH_ID AND a.MATCH_ID=c.MATCH_ID
--    AND (c.END_MODE_HDC=2.5 OR c.END_MODE_HDC=2.75)
--    AND MATCH_DATETIME<'2020-09-01'
--    AND a.HOME_FT_GOAL IS NOT NULL
    AND a.END_HDA_O_HKJC_H IS NOT NULL AND a.END_HKJC_HILO_HANDICAP IS NOT NULL AND a.END_HKJC_HILO_HI IS NOT NULL AND b.HOME_AVG_GF IS NOT NULL AND b.HOME_HOME_AVG_GF IS NOT NULL AND b.AWAY_AVG_GF IS NOT NULL AND b.AWAY_AWAY_AVG_GF IS NOT NULL
ORDER BY MATCH_DATETIME DESC;