--------------------------------------------------------
--  File created - Tuesday-October-06-2020   
--------------------------------------------------------
@D:\github-workspace\fbp-jupyter-notebook\db_schema\ASIAN_MERGE.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\ASIAN_RAW.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\BETFA_RAW.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\HDA_MEAN_MEDIAN.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\HDA_MERGE.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\HDA_RAW.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\HILO_MEAN_MEDIAN.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\HILO_MERGE.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\HILO_MERGE2.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\HILO_RAW.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\MATCH_INFO.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\MATCHDAY_STATUS.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\ML_PREDICT_ASIAN.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\ML_PREDICT_HILO.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\RECENT_RAW.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\ASIAN_MERGE_IDX1.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\ASIAN_RAW_IDX1.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\BETFA_RAW_IDX1.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\HDA_MEAN_MEDIAN_IDX1.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\HDA_MERGE_IDX1.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\HDA_RAW_IDX1.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\HILO_MEAN_MEDIAN_IDX1.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\HILO_MERGE_IDX1.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\HILO_RAW_IDX1.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\MATCH_INFO_IDX1.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\ML_PREDICT_ASIAN_IDX1.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\ML_PREDICT_HILO_IDX1.sql
@D:\github-workspace\fbp-jupyter-notebook\db_schema\RECENT_RAW_IDX1.sql
