--------------------------------------------------------
--  DDL for Table HILO_MERGE
--------------------------------------------------------

  CREATE TABLE "JW"."HILO_MERGE" 
   (	"MATCH_ID" NUMBER, 
	"HANDICAP_TYPE" NUMBER, 
	"HANDICAP" NUMBER, 
	"O_MACAU_HI" NUMBER, 
	"O_CROWN_HI" NUMBER, 
	"O_BET365_HI" NUMBER, 
	"O_EASYWIN_HI" NUMBER, 
	"O_WAITAK_HI" NUMBER, 
	"O_MINGSING_HI" NUMBER, 
	"O_10BET_HI" NUMBER, 
	"O_KAMBO_HI" NUMBER, 
	"O_12BET_HI" NUMBER, 
	"O_LEEKEE_HI" NUMBER, 
	"O_YINGYO_HI" NUMBER, 
	"O_18BET_HI" NUMBER, 
	"O_LADBROKES_HI" NUMBER, 
	"O_PINGBOK_HI" NUMBER, 
	"O_HKJC_HI" NUMBER, 
	"O_MACAU_LO" NUMBER, 
	"O_CROWN_LO" NUMBER, 
	"O_BET365_LO" NUMBER, 
	"O_EASYWIN_LO" NUMBER, 
	"O_WAITAK_LO" NUMBER, 
	"O_MINGSING_LO" NUMBER, 
	"O_10BET_LO" NUMBER, 
	"O_KAMBO_LO" NUMBER, 
	"O_12BET_LO" NUMBER, 
	"O_LEEKEE_LO" NUMBER, 
	"O_YINGYO_LO" NUMBER, 
	"O_18BET_LO" NUMBER, 
	"O_LADBROKES_LO" NUMBER, 
	"O_PINGBOK_LO" NUMBER, 
	"O_HKJC_LO" NUMBER, 
	"RESULT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
