--------------------------------------------------------
--  DDL for Table MATCH_INFO
--------------------------------------------------------

  CREATE TABLE "JW"."MATCH_INFO" 
   (	"MATCH_ID" NUMBER, 
	"MATCH_DATETIME" DATE, 
	"LEAGUE" VARCHAR2(50 BYTE), 
	"HOME_TEAM" VARCHAR2(50 BYTE), 
	"AWAY_TEAM" VARCHAR2(50 BYTE), 
	"HOME_FT_GOAL" NUMBER, 
	"AWAY_FT_GOAL" NUMBER, 
	"HOME_HT_GOAL" NUMBER, 
	"AWAY_HT_GOAL" NUMBER, 
	"DATA_DATE" VARCHAR2(8 BYTE), 
	"IS_COMPLETE" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
