--------------------------------------------------------
--  DDL for Table ML_PREDICT_ASIAN
--------------------------------------------------------

  CREATE TABLE "JW"."ML_PREDICT_ASIAN" 
   (	"ML_TYPE" VARCHAR2(20 BYTE), 
	"MATCH_ID" NUMBER, 
	"MATCH_DATETIME" DATE, 
	"LEAGUE" VARCHAR2(50 BYTE), 
	"HOME_TEAM" VARCHAR2(50 BYTE), 
	"AWAY_TEAM" VARCHAR2(50 BYTE), 
	"STR_A_MACAU_HDC" NUMBER, 
	"STR_A_MACAU_H" NUMBER, 
	"STR_A_MACAU_A" NUMBER, 
	"STR_HDA_MACAU_H" NUMBER, 
	"STR_HDA_MACAU_D" NUMBER, 
	"STR_HDA_MACAU_A" NUMBER, 
	"STR_A_HKJC_HDC" NUMBER, 
	"STR_A_HKJC_H" NUMBER, 
	"STR_A_HKJC_A" NUMBER, 
	"STR_HDA_HKJC_H" NUMBER, 
	"STR_HDA_HKJC_D" NUMBER, 
	"STR_HDA_HKJC_A" NUMBER, 
	"FAV_PROB" NUMBER, 
	"UND_PROB" NUMBER, 
	"MATCH_DATE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
