--------------------------------------------------------
--  DDL for Table ML_PREDICT_HILO
--------------------------------------------------------

  CREATE TABLE "JW"."ML_PREDICT_HILO" 
   (	"ML_TYPE" VARCHAR2(20 BYTE), 
	"MATCH_ID" NUMBER, 
	"MATCH_DATETIME" DATE, 
	"LEAGUE" VARCHAR2(50 BYTE), 
	"HOME_TEAM" VARCHAR2(50 BYTE), 
	"AWAY_TEAM" VARCHAR2(50 BYTE), 
	"STR_OU_MACAU_HDC" NUMBER, 
	"STR_OU_MACAU_HI" NUMBER, 
	"STR_OU_MACAU_LO" NUMBER, 
	"STR_OU_HKJC_HDC" NUMBER, 
	"STR_OU_HKJC_HI" NUMBER, 
	"STR_OU_HKJC_LO" NUMBER, 
	"HI_PROB" NUMBER, 
	"MATCH_DATE" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
