--------------------------------------------------------
--  DDL for Table RECENT_RAW
--------------------------------------------------------

  CREATE TABLE "JW"."RECENT_RAW" 
   (	"MATCH_ID" NUMBER, 
	"HOME_TOTAL_GF" NUMBER, 
	"HOME_TOTAL_GA" NUMBER, 
	"HOME_NET_GF" NUMBER, 
	"HOME_AVG_GF" NUMBER, 
	"HOME_WIN_RATE" NUMBER, 
	"HOME_DRAW_RATE" NUMBER, 
	"HOME_LOSE_RATE" NUMBER, 
	"HOME_HOME_GF" NUMBER, 
	"HOME_HOME_GA" NUMBER, 
	"HOME_HOME_NET_GF" NUMBER, 
	"HOME_HOME_AVG_GF" NUMBER, 
	"HOME_HOME_WIN_RATE" NUMBER, 
	"HOME_HOME_DRAW_RATE" NUMBER, 
	"HOME_HOME_LOSE_RATE" NUMBER, 
	"AWAY_TOTAL_GF" NUMBER, 
	"AWAY_TOTAL_GA" NUMBER, 
	"AWAY_NET_GF" NUMBER, 
	"AWAY_AVG_GF" NUMBER, 
	"AWAY_WIN_RATE" NUMBER, 
	"AWAY_DRAW_RATE" NUMBER, 
	"AWAY_LOSE_RATE" NUMBER, 
	"AWAY_AWAY_GF" NUMBER, 
	"AWAY_AWAY_GA" NUMBER, 
	"AWAY_AWAY_NET_GF" NUMBER, 
	"AWAY_AWAY_AVG_GF" NUMBER, 
	"AWAY_AWAY_WIN_RATE" NUMBER, 
	"AWAY_AWAY_DRAW_RATE" NUMBER, 
	"AWAY_AWAY_LOSE_RATE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "JW"."RECENT_RAW"."MATCH_ID" IS 'MatchID';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."HOME_TOTAL_GF" IS '主總入球';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."HOME_TOTAL_GA" IS '主總失球';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."HOME_NET_GF" IS '主淨勝球';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."HOME_AVG_GF" IS '主場均入球';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."HOME_WIN_RATE" IS '主勝率';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."HOME_DRAW_RATE" IS '主平率';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."HOME_LOSE_RATE" IS '主負率';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."HOME_HOME_GF" IS '主同主客入';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."HOME_HOME_GA" IS '主同主客失';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."HOME_HOME_NET_GF" IS '主同主客淨勝';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."HOME_HOME_AVG_GF" IS '主同主客均入';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."HOME_HOME_WIN_RATE" IS '主同主客勝';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."HOME_HOME_DRAW_RATE" IS '主同主客平';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."HOME_HOME_LOSE_RATE" IS '主同主客負';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."AWAY_TOTAL_GF" IS '客總入球';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."AWAY_TOTAL_GA" IS '客總失球';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."AWAY_NET_GF" IS '客淨勝球';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."AWAY_AVG_GF" IS '客場均入球';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."AWAY_WIN_RATE" IS '客勝率';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."AWAY_DRAW_RATE" IS '客平率';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."AWAY_LOSE_RATE" IS '客負率';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."AWAY_AWAY_GF" IS '客同主客入';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."AWAY_AWAY_GA" IS '客同主客失';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."AWAY_AWAY_NET_GF" IS '客同主客淨勝';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."AWAY_AWAY_AVG_GF" IS '客同主客均入';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."AWAY_AWAY_WIN_RATE" IS '客同主客勝';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."AWAY_AWAY_DRAW_RATE" IS '客同主客平';
   COMMENT ON COLUMN "JW"."RECENT_RAW"."AWAY_AWAY_LOSE_RATE" IS '客同主客負';
