SELECT empno,
    ename,
    deptno,
    sal,
    AVG(sal) OVER (PARTITION BY deptno) AS mean_sal_by_dept
FROM   emp;

-- HILO_MEAN_VIEW
SELECT MATCH_ID,MATCH_DATETIME,LEAGUE,HOME_TEAM,AWAY_TEAM,HOME_FT_GOAL,AWAY_FT_GOAL,HOME_HT_GOAL,AWAY_HT_GOAL,HANDICAP_TYPE,HANDICAP,HI_IND,LO_IND,BOOKMAKER_COUNT,HI_MEAN,HI_MEDIAN,HI_DIFF,O_MACAU_HI,O_CROWN_HI,O_BET365_HI,O_EASYWIN_HI,O_WAITAK_HI,O_MINGSING_HI,O_10BET_HI,O_KAMBO_HI,O_12BET_HI,O_LEEKEE_HI,O_YINGYO_HI,O_18BET_HI,O_LADBROKES_HI,O_PINGBOK_HI,O_HKJC_HI
FROM HILO_MEAN_VIEW WHERE HANDICAP_TYPE=0 AND HI_IND=1 AND LO_IND=0 ORDER BY MATCH_DATETIME DESC;

--
SELECT 
    a.MATCH_ID,
    a.MATCH_DATETIME,
    a.LEAGUE,
    a.HOME_TEAM,
    a.AWAY_TEAM,
    a.HOME_FT_GOAL,
    a.AWAY_FT_GOAL,
    DECODE(a.GAME_RESULT,'D','A',a.GAME_RESULT),
    a.HOME_MEAN,
    a.HOME_MEDIAN,
    a.HOME_DIFF,
    a.O_HKJC_H,
    a.DRAW_MEAN,
    a.DRAW_MEDIAN,
    a.DRAW_DIFF,
    a.O_HKJC_D,
    a.AWAY_MEAN,
    a.AWAY_MEDIAN,
    a.AWAY_DIFF,
    a.O_HKJC_A,
    c.BETFA_HOME_HC_IDX,
    c.BETFA_DRAW_HC_IDX,
    c.BETFA_AWAY_HC_IDX,
    c.BETFA_HOME_TRADE_RATE,
    c.BETFA_DRAW_TRADE_RATE,
    c.BETFA_AWAY_TRADE_RATE,
    c.TOTAL_HOME_BUYER-c.TOTAL_HOME_SELLER,
    c.TOTAL_DRAW_BUYER-c.TOTAL_DRAW_SELLER,
    c.TOTAL_AWAY_BUYER-c.TOTAL_AWAY_SELLER
FROM
    HDA_MEAN_VIEW a,
    BETFA_RAW c
WHERE
    a.MATCH_ID=c.MATCH_ID
ORDER BY MATCH_DATETIME DESC
    ;

-- AI
SELECT 
    a.MATCH_ID,
    a.MATCH_DATETIME,
    a.LEAGUE,
    a.HOME_TEAM,
    a.AWAY_TEAM,
    a.HOME_FT_GOAL,
    a.AWAY_FT_GOAL,
    DECODE(a.GAME_RESULT,'D','A',a.GAME_RESULT),
    'Xnew = [[' ||
    a.HOME_MEAN || ',' ||
    a.HOME_MEDIAN || ',' ||
    a.HOME_DIFF || ',' ||
    a.O_HKJC_H || ',' ||
    a.DRAW_MEAN || ',' ||
    a.DRAW_MEDIAN || ',' ||
    a.DRAW_DIFF || ',' ||
    a.O_HKJC_D || ',' ||
    a.AWAY_MEAN || ',' ||
    a.AWAY_MEDIAN || ',' ||
    a.AWAY_DIFF || ',' ||
    a.O_HKJC_A || ',' ||
    c.BETFA_HOME_HC_IDX || ',' ||
    c.BETFA_DRAW_HC_IDX || ',' ||
    c.BETFA_AWAY_HC_IDX || ',' ||
    c.BETFA_HOME_TRADE_RATE || ',' ||
    c.BETFA_DRAW_TRADE_RATE || ',' ||
    c.BETFA_AWAY_TRADE_RATE || ',' ||
    TO_CHAR(c.TOTAL_HOME_BUYER-c.TOTAL_HOME_SELLER) || ',' ||
    TO_CHAR(c.TOTAL_DRAW_BUYER-c.TOTAL_DRAW_SELLER) || ',' ||
    TO_CHAR(c.TOTAL_AWAY_BUYER-c.TOTAL_AWAY_SELLER) || ']]'
FROM
    HDA_MEAN_VIEW a,
    BETFA_RAW c
WHERE
    a.MATCH_ID=c.MATCH_ID
    AND HOME_FT_GOAL IS NOT NULL
    ;

-- NO ASIAN
SELECT
    GAME_RESULT || ',' ||
    STR_HOME_MEAN || ',' ||
    STR_HOME_MEDIAN || ',' ||
    STR_HOME_DIFF || ',' ||
    STR_HDA_HKJC_H || ',' ||
    STR_DRAW_MEAN || ',' ||
    STR_DRAW_MEDIAN || ',' ||
    STR_DRAW_DIFF || ',' ||
    STR_HDA_HKJC_D || ',' ||
    STR_AWAY_MEAN || ',' ||
    STR_AWAY_MEDIAN || ',' ||
    STR_AWAY_DIFF || ',' ||
    STR_HDA_HKJC_A || ',' ||
    END_HOME_MEAN || ',' ||
    END_HOME_MEDIAN || ',' ||
    END_HOME_DIFF || ',' ||
    END_HDA_HKJC_H || ',' ||
    END_DRAW_MEAN || ',' ||
    END_DRAW_MEDIAN || ',' ||
    END_DRAW_DIFF || ',' ||
    END_HDA_HKJC_D || ',' ||
    END_AWAY_MEAN || ',' ||
    END_AWAY_MEDIAN || ',' ||
    END_AWAY_DIFF || ',' ||
    END_HDA_HKJC_A || ',' ||
    BETFA_HOME_HC_IDX || ',' ||
    BETFA_DRAW_HC_IDX || ',' ||
    BETFA_AWAY_HC_IDX || ',' ||
    BETFA_HOME_TRADE_RATE || ',' ||
    BETFA_DRAW_TRADE_RATE || ',' ||
    BETFA_AWAY_TRADE_RATE || ',' ||
    HOME_TIX_DIFF || ',' ||
    DRAW_TIX_DIFF || ',' ||
    AWAY_TIX_DIFF || ',' ||
    STR_ASIAN_HDC || ',' ||
    STR_ASIAN_AVG || ',' ||
    STR_ASIAN_MEDIAN || ',' ||
    STR_ASIAN_AVG_DIFF || ',' ||
    -- STR_HKJC_HDC || ',' ||
    -- STR_ASIAN_HKJC_H || ',' ||
    -- STR_ASIAN_HKJC_A || ',' ||
    END_ASIAN_HDC || ',' ||
    END_ASIAN_AVG || ',' ||
    END_ASIAN_MEDIAN || ',' ||
    END_ASIAN_AVG_DIFF 
    -- || ',' ||
    -- END_HKJC_HDC || ',' ||
    -- END_ASIAN_HKJC_H || ',' ||
    -- END_ASIAN_HKJC_A
FROM ML_VIEW 
WHERE MATCH_DATETIME < '2020-09-08'
AND GAME_RESULT IS NOT NULL
AND STR_HOME_MEAN IS NOT NULL
AND STR_HOME_MEDIAN IS NOT NULL
AND STR_HOME_DIFF IS NOT NULL
AND STR_HDA_HKJC_H IS NOT NULL
AND STR_DRAW_MEAN IS NOT NULL
AND STR_DRAW_MEDIAN IS NOT NULL
AND STR_DRAW_DIFF IS NOT NULL
AND STR_HDA_HKJC_D IS NOT NULL
AND STR_AWAY_MEAN IS NOT NULL
AND STR_AWAY_MEDIAN IS NOT NULL
AND STR_AWAY_DIFF IS NOT NULL
AND STR_HDA_HKJC_A IS NOT NULL
AND END_HOME_MEAN IS NOT NULL
AND END_HOME_MEDIAN IS NOT NULL
AND END_HOME_DIFF IS NOT NULL
AND END_HDA_HKJC_H IS NOT NULL
AND END_DRAW_MEAN IS NOT NULL
AND END_DRAW_MEDIAN IS NOT NULL
AND END_DRAW_DIFF IS NOT NULL
AND END_HDA_HKJC_D IS NOT NULL
AND END_AWAY_MEAN IS NOT NULL
AND END_AWAY_MEDIAN IS NOT NULL
AND END_AWAY_DIFF IS NOT NULL
AND END_HDA_HKJC_A IS NOT NULL
AND BETFA_HOME_HC_IDX IS NOT NULL
AND BETFA_DRAW_HC_IDX IS NOT NULL
AND BETFA_AWAY_HC_IDX IS NOT NULL
AND BETFA_HOME_TRADE_RATE IS NOT NULL
AND BETFA_DRAW_TRADE_RATE IS NOT NULL
AND BETFA_AWAY_TRADE_RATE IS NOT NULL
AND HOME_TIX_DIFF IS NOT NULL
AND DRAW_TIX_DIFF IS NOT NULL
AND AWAY_TIX_DIFF IS NOT NULL
AND STR_ASIAN_HDC IS NOT NULL
AND STR_ASIAN_AVG IS NOT NULL
AND STR_ASIAN_MEDIAN IS NOT NULL
AND STR_ASIAN_AVG_DIFF IS NOT NULL
-- AND STR_HKJC_HDC IS NOT NULL
-- AND STR_ASIAN_HKJC_H IS NOT NULL
-- AND STR_ASIAN_HKJC_A IS NOT NULL
AND END_ASIAN_HDC IS NOT NULL
AND END_ASIAN_AVG IS NOT NULL
AND END_ASIAN_MEDIAN IS NOT NULL
AND END_ASIAN_AVG_DIFF IS NOT NULL
-- AND END_HKJC_HDC IS NOT NULL
-- AND END_ASIAN_HKJC_H IS NOT NULL
-- AND END_ASIAN_HKJC_A IS NOT NULL
ORDER BY MATCH_DATETIME
; 



SELECT 
    info.MATCH_ID,
    info.MATCH_DATETIME,
    info.LEAGUE,
    info.HOME_TEAM,
    info.AWAY_TEAM,
    info.HOME_FT_GOAL,
    info.AWAY_FT_GOAL,
    info.HOME_HT_GOAL,
    info.AWAY_HT_GOAL,
    CASE
        WHEN e.STR_MODE_HDC>0 AND info.HOME_FT_GOAL-info.AWAY_FT_GOAL>e.STR_MODE_HDC THEN '上盤'
        WHEN e.STR_MODE_HDC<0 AND info.HOME_FT_GOAL-info.AWAY_FT_GOAL>=e.STR_MODE_HDC THEN '下盤'
        WHEN e.STR_MODE_HDC=0 AND info.HOME_FT_GOAL-info.AWAY_FT_GOAL>e.STR_MODE_HDC THEN '主'
        WHEN e.STR_MODE_HDC=0 AND info.HOME_FT_GOAL-info.AWAY_FT_GOAL=e.STR_MODE_HDC THEN '走'
        WHEN e.STR_MODE_HDC=0 AND info.HOME_FT_GOAL-info.AWAY_FT_GOAL<e.STR_MODE_HDC THEN '客'
        ELSE ''
    END,
    CASE
        WHEN info.HOME_FT_GOAL>info.AWAY_FT_GOAL THEN 'H'
        WHEN info.HOME_FT_GOAL<info.AWAY_FT_GOAL THEN 'A'
        WHEN info.HOME_FT_GOAL IS NULL THEN NULL
        ELSE 'D'
    END,
    a.MATCH_HANDICAP,
    a.HOME_MEAN,
    a.HOME_MEDIAN,
    a.DRAW_MEAN,
    a.DRAW_MEDIAN,
    a.AWAY_MEAN,
    a.AWAY_MEDIAN,
    a.O_MACAU_H,
    a.O_MACAU_D,
    a.O_MACAU_A,
    a.O_HKJC_H,
    a.O_HKJC_D,
    a.O_HKJC_A,
    b.MATCH_HANDICAP,
    b.HOME_MEAN,
    b.HOME_MEDIAN,
    b.DRAW_MEAN,
    b.DRAW_MEDIAN,
    b.AWAY_MEAN,
    b.AWAY_MEDIAN,
    b.O_MACAU_H,
    b.O_MACAU_D,
    b.O_MACAU_A,
    b.O_HKJC_H,
    b.O_HKJC_D,
    b.O_HKJC_A,
    c.START_HANDICAP,
    c.START_HI,
    c.START_LO,
    d.START_HANDICAP,
    d.START_HI,
    d.START_LO,
    c.END_HANDICAP,
    c.END_HI,
    c.END_LO,
    d.END_HANDICAP,
    d.END_HI,
    d.END_LO,
    e.STR_MODE_CNT,
    e.STR_MODE_HDC,
    e.STR_O_AVG,
    e.STR_O_MEDIAN,
    e.STR_MACAU_HDC,
    e.STR_O_MACAU_H,
    e.STR_O_MACAU_A,
    e.STR_HKJC_HDC,
    e.STR_O_HKJC_H,
    e.STR_O_HKJC_A,
    e.END_MODE_CNT,
    e.END_MODE_HDC,
    e.END_O_AVG,
    e.END_O_MEDIAN,
    e.END_MACAU_HDC,
    e.END_O_MACAU_H,
    e.END_O_MACAU_A,
    e.END_HKJC_HDC,
    e.END_O_HKJC_H,
    e.END_O_HKJC_A
FROM HDA_MEAN_VIEW a, HDA_MEAN_VIEW b, HILO_RAW c, HILO_RAW d, ASIAN_MERGE_VIEW e, MATCH_INFO info
WHERE
    a.MATCH_ID=b.MATCH_ID AND a.MATCH_ID=c.MATCH_ID AND a.MATCH_ID=d.MATCH_ID AND a.MATCH_ID=e.MATCH_ID AND a.MATCH_ID=info.MATCH_ID
    AND a.HANDICAP_TYPE=0 AND b.HANDICAP_TYPE=1
    AND c.BOOKMAKER='澳门' AND c.LINE='盘口1'
    AND d.BOOKMAKER='香港马会' AND d.LINE='盘口1'
ORDER BY info.MATCH_DATETIME DESC;



SELECT a.MATCH_ID, a.MATCH_DATETIME, a.LEAGUE, a.HOME_TEAM, a.AWAY_TEAM, a.HOME_FT_GOAL, a.AWAY_FT_GOAL, 
ROUND(a.STR_HDA_HOME_MEAN,4) AS HDA_H_MEAN, a.STR_HDA_O_MACAU_H, a.STR_HDA_O_HKJC_H, 
a.STR_ASIAN_MODE_HDC, a.STR_ASIAN_O_AVG_HOME, a.STR_ASIAN_MACAU_HDC, a.STR_ASIAN_O_MACAU_H, a.STR_ASIAN_HKJC_HDC, a.STR_ASIAN_O_HKJC_H
FROM FULL_VIEW a
WHERE 
STR_ASIAN_HKJC_HDC=-0.75 AND END_ASIAN_HKJC_HDC=-0.75 AND STR_ASIAN_O_HKJC_H<0.7 AND END_ASIAN_O_HKJC_H>0.78
ORDER BY ROUND(a.STR_HDA_HOME_MEAN,4)
;
