-- 82.3% D/A
select hda_result,count(1)
from full_view 
where (str_hda_o_hkjc_h-str_hda_home_mean>0 and str_hda_o_hkjc_d-str_hda_draw_mean>0 and str_hda_o_hkjc_a-str_hda_away_mean<0 and str_hda_o_macau_h-str_hda_home_mean>0 and str_hda_o_macau_d-str_hda_draw_mean>0 and str_hda_o_macau_a-str_hda_away_mean<0) 
or (str_hda_o_hkjc_h-str_hda_home_mean<0 and str_hda_o_hkjc_d-str_hda_draw_mean>0 and str_hda_o_hkjc_a-str_hda_away_mean>0 and str_hda_o_macau_h-str_hda_home_mean<0 and str_hda_o_macau_d-str_hda_draw_mean>0 and str_hda_o_macau_a-str_hda_away_mean>0)
and STR_MACAU_HILO_HANDICAP=STR_HKJC_HILO_HANDICAP and STR_HKJC_HILO_LO<STR_HKJC_HILO_HI
group by hda_result;




select MATCH_ID, MATCH_DATETIME, LEAGUE, HOME_TEAM, AWAY_TEAM, HOME_FT_GOAL, AWAY_FT_GOAL, HOME_HT_GOAL, AWAY_HT_GOAL, STR_HKJC_HILO_HANDICAP, CASE WHEN HOME_FT_GOAL+AWAY_FT_GOAL>2 THEN 'HI' ELSE 'LO' END, HDA_RESULT, STR_HDA_HOME_MEAN, STR_HDA_DRAW_MEAN, STR_HDA_AWAY_MEAN, STR_HDA_O_MACAU_H, STR_HDA_O_MACAU_D, STR_HDA_O_MACAU_A, STR_HDA_O_HKJC_H, STR_HDA_O_HKJC_D, STR_HDA_O_HKJC_A, STR_MACAU_HILO_HANDICAP, STR_MACAU_HILO_HI, STR_MACAU_HILO_LO, STR_HKJC_HILO_HANDICAP, STR_HKJC_HILO_HI, STR_HKJC_HILO_LO

select CASE WHEN HOME_FT_GOAL+AWAY_FT_GOAL>2 THEN 'HI' ELSE 'LO' END as result,count(1)
from full_view 
where ((str_hda_o_hkjc_h-str_hda_home_mean>0 and str_hda_o_hkjc_d-str_hda_draw_mean>0 and str_hda_o_hkjc_a-str_hda_away_mean<0) 
or (str_hda_o_hkjc_h-str_hda_home_mean<0 and str_hda_o_hkjc_d-str_hda_draw_mean>0 and str_hda_o_hkjc_a-str_hda_away_mean>0))
group by result;


select * from full_view where str_hda_o_hkjc_h = 1.32 order by hda_result;


-- HILO
select MATCH_ID, MATCH_DATETIME, LEAGUE, HOME_TEAM, AWAY_TEAM, HOME_FT_GOAL, AWAY_FT_GOAL, HOME_HT_GOAL, AWAY_HT_GOAL, STR_HKJC_HILO_HANDICAP, HILO_MACAU_RESULT, HILO_HKJC_RESULT, HDA_RESULT, STR_HDA_HOME_MEAN, STR_HDA_DRAW_MEAN, STR_HDA_AWAY_MEAN, STR_HDA_O_MACAU_H, STR_HDA_O_MACAU_D, STR_HDA_O_MACAU_A, STR_HDA_O_HKJC_H, STR_HDA_O_HKJC_D, STR_HDA_O_HKJC_A, STR_MACAU_HILO_HANDICAP, STR_MACAU_HILO_HI, STR_MACAU_HILO_LO, STR_HKJC_HILO_HANDICAP, STR_HKJC_HILO_HI, STR_HKJC_HILO_LO
--select CASE WHEN HOME_FT_GOAL+AWAY_FT_GOAL>2 THEN 'HI' ELSE 'LO' END,count(1)
from full_view 
where ((str_hda_o_hkjc_h-str_hda_home_mean>0 and str_hda_o_hkjc_d-str_hda_draw_mean>0 and str_hda_o_hkjc_a-str_hda_away_mean<0) 
or (str_hda_o_hkjc_h-str_hda_home_mean<0 and str_hda_o_hkjc_d-str_hda_draw_mean>0 and str_hda_o_hkjc_a-str_hda_away_mean>0))
;

-- TIX_SIGN
HI	+	-	-	84
LO	+	-	-	62
HI	-	-	+	80
LO	-	-	+	67

-- HKJC_SIGN
HI	-	+	141
LO	-	+	108


SELECT
    HILO_MACAU_RESULT,
    -- STR_HDA_HOME_MEAN_MACAU_SIGN,
    -- STR_HDA_DRAW_MEAN_MACAU_SIGN,
    -- STR_HDA_AWAY_MEAN_MACAU_SIGN,
    -- END_HDA_HOME_MEAN_MACAU_SIGN,
    -- END_HDA_DRAW_MEAN_MACAU_SIGN,
    -- END_HDA_AWAY_MEAN_MACAU_SIGN,
    -- STR_HILO_HI_MACAU_SIGN,
    -- STR_HILO_LO_MACAU_SIGN,
    -- END_HILO_HI_MACAU_SIGN,
    -- END_HILO_LO_MACAU_SIGN,
--     STR_HDA_HOME_MEAN_HKJC_SIGN,
--     STR_HDA_DRAW_MEAN_HKJC_SIGN,
--     STR_HDA_AWAY_MEAN_HKJC_SIGN,
    -- END_HDA_HOME_MEAN_HKJC_SIGN,
    -- END_HDA_DRAW_MEAN_HKJC_SIGN,
    -- END_HDA_AWAY_MEAN_HKJC_SIGN,
     STR_HILO_HI_HKJC_SIGN,
     STR_HILO_LO_HKJC_SIGN,
    -- END_HILO_HI_HKJC_SIGN,
    -- END_HILO_LO_HKJC_SIGN,
--    BETFA_HOME_HC_IDX_SIGN,
--    BETFA_DRAW_HC_IDX_SIGN,
--    BETFA_AWAY_HC_IDX_SIGN,
--     TOTAL_HOME_TIX_SIGN,
--     TOTAL_DRAW_TIX_SIGN,
--     TOTAL_AWAY_TIX_SIGN,
--     TOTAL_HOME_TIX,
--    TOTAL_DRAW_TIX,
--    TOTAL_AWAY_TIX
    COUNT(1)
FROM SIMP_FULL_VIEW
WHERE 
    -- HILO_MACAU_RESULT='HI'
    -- AND 
    BETFA_HOME_HC_IDX_SIGN IS NOT NULL
    AND BETFA_DRAW_HC_IDX_SIGN IS NOT NULL
    AND BETFA_AWAY_HC_IDX_SIGN IS NOT NULL
    AND TOTAL_HOME_TIX_SIGN IS NOT NULL
    AND TOTAL_DRAW_TIX_SIGN IS NOT NULL
    AND TOTAL_AWAY_TIX_SIGN IS NOT NULL
    AND HILO_MACAU_RESULT IS NOT NULL
GROUP BY 
    
    -- STR_HDA_HOME_MEAN_MACAU_SIGN,
    -- STR_HDA_DRAW_MEAN_MACAU_SIGN,
    -- STR_HDA_AWAY_MEAN_MACAU_SIGN,
    -- END_HDA_HOME_MEAN_MACAU_SIGN,
    -- END_HDA_DRAW_MEAN_MACAU_SIGN,
    -- END_HDA_AWAY_MEAN_MACAU_SIGN,
    -- STR_HILO_HI_MACAU_SIGN,
    -- STR_HILO_LO_MACAU_SIGN,
    -- END_HILO_HI_MACAU_SIGN,
    -- END_HILO_LO_MACAU_SIGN,
--     STR_HDA_HOME_MEAN_HKJC_SIGN,
--     STR_HDA_DRAW_MEAN_HKJC_SIGN,
--     STR_HDA_AWAY_MEAN_HKJC_SIGN,
    -- END_HDA_HOME_MEAN_HKJC_SIGN,
    -- END_HDA_DRAW_MEAN_HKJC_SIGN,
    -- END_HDA_AWAY_MEAN_HKJC_SIGN,
     STR_HILO_HI_HKJC_SIGN,
     STR_HILO_LO_HKJC_SIGN,
    -- END_HILO_HI_HKJC_SIGN,
    -- END_HILO_LO_HKJC_SIGN,
--    BETFA_HOME_HC_IDX_SIGN,
--    BETFA_DRAW_HC_IDX_SIGN,
--    BETFA_AWAY_HC_IDX_SIGN
    -- ,
--     TOTAL_HOME_TIX_SIGN,
--     TOTAL_DRAW_TIX_SIGN,
--     TOTAL_AWAY_TIX_SIGN,
    HILO_MACAU_RESULT
ORDER BY 
    
--    STR_HDA_HOME_MEAN_HKJC_SIGN,
--     STR_HDA_DRAW_MEAN_HKJC_SIGN,
--     STR_HDA_AWAY_MEAN_HKJC_SIGN,
--    TOTAL_HOME_TIX_SIGN,
--     TOTAL_DRAW_TIX_SIGN,
--     TOTAL_AWAY_TIX_SIGN,
STR_HILO_HI_HKJC_SIGN,
     STR_HILO_LO_HKJC_SIGN,
    COUNT(1) DESC
;


-- 下盤
SELECT
    MATCH_ID,
    MATCH_DATETIME,
    LEAGUE,
    HOME_TEAM,
    AWAY_TEAM,
    HOME_FT_GOAL,
    AWAY_FT_GOAL,
    HOME_HT_GOAL,
    AWAY_HT_GOAL,
    STR_ASIAN_MODE_HDC,
    STR_ASIAN_O_AVG_HOME,
    STR_ASIAN_O_AVG_AWAY,
    END_ASIAN_MODE_HDC,
    END_ASIAN_O_AVG_HOME,
    END_ASIAN_O_AVG_AWAY,
    STR_HKJC_HILO_HANDICAP,
    STR_AVG_HILO_HI,
    STR_AVG_HILO_LO,
    END_HKJC_HILO_HANDICAP,
    END_AVG_HILO_HI,
    END_AVG_HILO_LO,
    
    STR_ASIAN_HKJC_HDC,
    STR_ASIAN_O_HKJC_H,
    STR_ASIAN_O_HKJC_A,
    END_ASIAN_HKJC_HDC,
    END_ASIAN_O_HKJC_H,
    END_ASIAN_O_HKJC_A,
    STR_HKJC_HILO_HANDICAP,
    STR_HKJC_HILO_HI,
    STR_HKJC_HILO_LO,
    END_HKJC_HILO_HANDICAP,
    END_HKJC_HILO_HI,
    END_HKJC_HILO_LO,
    STR_ASIAN_MACAU_HDC,
    STR_ASIAN_O_MACAU_H,
    STR_ASIAN_O_MACAU_A,
    END_ASIAN_MACAU_HDC,
    END_ASIAN_O_MACAU_H,
    END_ASIAN_O_MACAU_A,
    STR_MACAU_HILO_HANDICAP,
    STR_MACAU_HILO_HI,
    STR_MACAU_HILO_LO,
    END_MACAU_HILO_HANDICAP,
    END_MACAU_HILO_HI,
    END_MACAU_HILO_LO,
    CASE 
        WHEN STR_ASIAN_MODE_HDC=0.25 AND STR_ASIAN_O_HKJC_A<STR_ASIAN_O_HKJC_H AND STR_HKJC_HILO_LO<STR_HKJC_HILO_HI AND END_HKJC_HILO_LO<=STR_HKJC_HILO_LO THEN '下盤'
        WHEN STR_ASIAN_MODE_HDC=-0.25 AND STR_ASIAN_O_HKJC_A>STR_ASIAN_O_HKJC_H AND STR_HKJC_HILO_LO<STR_HKJC_HILO_HI AND END_HKJC_HILO_LO<=STR_HKJC_HILO_LO THEN '下盤'
        ELSE NULL
    END AS PREDICT_STR_HKJC,
    CASE 
        WHEN STR_ASIAN_MODE_HDC=0.25 AND STR_ASIAN_O_MACAU_A<STR_ASIAN_O_MACAU_H AND ((STR_MACAU_HILO_HANDICAP=2.5 AND STR_MACAU_HILO_LO<STR_MACAU_HILO_HI) OR STR_MACAU_HILO_HANDICAP<2.5) AND ((END_MACAU_HILO_HANDICAP=2.5 AND END_MACAU_HILO_LO<END_MACAU_HILO_HI) OR END_MACAU_HILO_HANDICAP<2.5) THEN '下盤'
        WHEN STR_ASIAN_MODE_HDC=-0.25 AND STR_ASIAN_O_MACAU_A>STR_ASIAN_O_MACAU_H AND ((STR_MACAU_HILO_HANDICAP=2.5 AND STR_MACAU_HILO_LO<STR_MACAU_HILO_HI) OR STR_MACAU_HILO_HANDICAP<2.5) AND ((END_MACAU_HILO_HANDICAP=2.5 AND END_MACAU_HILO_LO<END_MACAU_HILO_HI) OR END_MACAU_HILO_HANDICAP<2.5) THEN '下盤'
        ELSE NULL
    END AS PREDICT_STR_MACAU
FROM FULL_VIEW
WHERE 
    (STR_ASIAN_MODE_HDC=0.25 OR STR_ASIAN_MODE_HDC=-0.25)
    AND (END_ASIAN_MODE_HDC=0.25 OR END_ASIAN_MODE_HDC=-0.25) 
    AND (END_ASIAN_HKJC_HDC=0.25 OR END_ASIAN_HKJC_HDC=-0.25)
ORDER BY MATCH_DATETIME DESC;