OPTIONS (ERRORS=33903)
LOAD DATA 
INFILE 'D:\github-workspace\fbp-jupyter-notebook\backup_20201005\ASIAN_RAW_DATA_TABLE.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "JW"."ASIAN_RAW"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"MATCH_ID" ,
"BOOKMAKER" CHAR (20),
"LINE" CHAR (20),
"START_HOME" ,
"START_HANDICAP" ,
"START_AWAY" ,
"END_HOME" ,
"END_HANDICAP" ,
"END_AWAY" ,
"IS_MERGED" CHAR (1))
