OPTIONS (ERRORS=37572)
LOAD DATA 
INFILE 'D:\github-workspace\fbp-jupyter-notebook\backup_20201005\HILO_RAW_DATA_TABLE.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "JW"."HILO_RAW"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"MATCH_ID" ,
"BOOKMAKER" CHAR (20),
"LINE" CHAR (20),
"START_HI" ,
"START_HANDICAP" ,
"START_LO" ,
"END_HI" ,
"END_HANDICAP" ,
"END_LO" ,
"IS_MERGED" CHAR (1))
