OPTIONS (ERRORS=54)
LOAD DATA 
INFILE 'D:\github-workspace\fbp-jupyter-notebook\backup_20201005\MATCHDAY_STATUS_DATA_TABLE.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "JW"."MATCHDAY_STATUS"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"MATCH_DATE" ,
"IS_SCRAPED" CHAR (1))
